# Generated by Django 4.2.16 on 2024-12-04 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='temaWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='articuloWiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=128, null=True)),
                ('contenido', models.CharField(blank=True, max_length=1024, null=True)),
                ('temaRelacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='wikiApp.temawiki')),
            ],
        ),
    ]
